[metadata]
version = attr: ctadl_jadx_fact_generator_plugin.__version__
description = CTADL JADX fact generator plugin
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/sandialabs/ctadl-jadx-fact-generator
project_urls =
    Bug Tracker = https://github.com/sandialabs/ctadl-jadx-fact-generator/issues
classifiers =
    Programming Language :: Python :: 3.9
    Environment :: Console
    Environment :: Plugins
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX
license_files = LICENSE.txt

[options]
zip_safe = False
packages = find:
package_dir =
    = src
include_package_data = True
python_requires = >=3.9
install_requires =

[options.packages.find]
where = src
